### ISSUE TITLE
Unable to map nested json request in schema.js 

### ISSUE THREAD

**Issue by rishirajgarg** [nordsimon/elasticsearch-graphql#5]
Hi,

Could you please help me to know how can I map nested JSON request (fetched from elastic search) in schema.js. I tried GraphQLObjectType in schema.js but it didn't work.
Below is the sample JSON(**from Elastic search**) which I am using in my project. Though the simple type eg- _index,_type,_id can be mapped easily in schema.js but I want to know how can I map nested json request for _souce field (refer below).

      {
        "_index": "bank",
        "_type": "account",
        "_id": "AVm0-nXVZM1fEu5djUwI",
        "_score": 1,
        "_source": 
              {
                 "account_number": 0,
                 "state": "CO"
              }
      }

Sample Taken from below example:-
https://github.com/nordsimon/elasticsearch-graphql-server-example

**Comment by nordsimon** [comment]
Hi rishi

I am sorry for the late answer. Unfortunately my answer is very easy, when I built the parser elastic search was in version 2.3. Since then I haven't used at my current work and Es 5 was released. In this release they have changed a lot behavoiur regarding mapping and nested documents

At the moment I won't have time to fix this, I will update the readme and the packag to warn if Es 5 is used. So at the moment my only solution for you is to use Es 2.3

Regards
Simon

**Comment by rishirajgarg** [comment]
Hi Simon,
Thanks for  your response. Based on your suggestion I changed by ES version to 2.3 but the issue remain as its is. could be because of the reason that  json response structure generated by ES2.3.1 and ES 5.0 is same.

###ES 2.3
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "bank",
      "_type" : "account",
      "_id" : "1",
      "_score" : 1.0,
      "_source" : {
        "firstnam" : "Bradshaq2"
      }
    } ]
  }
}

#############
ES 5.0

{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 7,
    "max_score": 1,
    "hits": [
      {
        "_index": "bank",
        "_type": "account",
        "_id": "AVm0-nXVZM1fEu5djUwI",
        "_score": 1,
        "_source": {
          "firstname": "Bradshaw",
        }
      }
      }
    ]
  }
}

please note that this time I created a single document for field  "firstnam"  in both the versions.
If possible could you please tell me what all options are available  to integrate elasticsearch with GraphQL. appreciate if you could spare sometime to help me with the fix.  Also, Appreciate if you could help me to know if there is any other options available for ElasticSearch and GraphQL integration.

**Comment by nordsimon** [comment]
Hi. I just posted a deprecation notice, i have no good solution for elasticsearch-graphql integration other than handcrafted own solutions. would love to have some more time and make this better but unfortunely that is not possible at the moment
